[preset]
Name="Yaru"
Author="GradienceTeam"
Maintainer="GradienceTeam"
Description="Ubuntu default theme"
Support="https://matrix.to/#/#gradience-presets:envs.net"
Version="0.3.1"
Badges=["world"]
URL="https://raw.githubusercontent.com/gradience-presets/yaru/main/yaru.toml"

[light]
variables = {
}
palette = {
}

# This section can be skiped 
[light.css]
gtk3=""
gtk4=""

[dark]
variables = {
}
# If there's not palette, gradience will use the Adwaita's default palette

# A red variant
[red]
variables = {
}
